version: 2.1
description: # The purpose of this orb

orbs:
  node:
    executors:
      default:
        docker:
          - image: cimg/node:10.20
      aws-cli:
        docker:
          - image: amazon/aws-cli
    commands:
      init:
        description: "make init command"
        parameters:
          init_command:
            type: string
            default: make init
        steps:
          - run: "<< parameters.init_command >>"
      test:
        description: "make test command"
        parameters:
          test_command:
            type: string
            default: make test
        steps:
          - run: "<< parameters.test_command >>"
      build:
        description: "make build command"
        parameters:
          build_command:
            type: string
            default: make build
        steps:
          - run: "<< parameters.build_command >>"
      deploy:
        description: "make deploy command"
        parameters:
          deploy_command:
            type: string
            default: make deploy
        steps:
          - run: "<< parameters.deploy_command >>"
jobs:
  development:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "code/package-lock.json" }}
            - npm-deps-
      - node/init
      - save_cache:
          key: npm-deps-{{ checksum "code/package-lock.json" }}
          paths:
            - code/node_modules
      - node/build
      - node/test
      - node/deploy

  test:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "code/package-lock.json" }}
            - npm-deps-
      - node/init
      - save_cache:
          key: npm-deps-{{ checksum "code/package-lock.json" }}
          paths:
            - code/node_modules
      - node/build
      - node/test
      - node/deploy

  production:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "code/package-lock.json" }}
            - npm-deps-
      - node/init
      - save_cache:
          key: npm-deps-{{ checksum "code/package-lock.json" }}
          paths:
            - code/node_modules
      - node/build
      - node/test
      - node/deploy

workflows:
  main:
    jobs:
      - development
      - test:
          requires:
            - development
      - production:
          requires:
            - test
