version: 2.1
description: # The purpose of this orb

orbs:
  node:
    executors:
      node:
        docker:
          - image: cimg/python:3.7-node
    # commands:
    #   install:
    #     steps:
    #       - run:
    #           name: Install NVM
    #           command: curl -o- https://raw.githubusercontent.com/creationix/nvm/v${NVM_VERSION}/install.sh | bash \
    #       - run:
    #           name: activate profile
    #           command: |
    #             echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
    #             echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV

    jobs:
      install:
        executor: node
        steps:
          - run:
              name: Install NVM
              command: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
          - run:
              name: activate profile
              command: |
                echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
                echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
          - run:
              name: install NVM_DIR=$HOME/.nvm
              command: nvm install

      checkout:
        executor: node
        steps:
          - checkout

      verify-versions:
        executor: node
        steps:
          - run:
              name: npm version
              command: npm --version
          - run:
              name: node version
              command: node --version
      init:
        executor: node
        steps:
          - restore_cache:
              keys:
                - npm-deps-{{ checksum "code/package-lock.json" }}
                - npm-deps-
          - run:
              name: Running make init
              command: make init
          - save_cache:
              key: npm-deps-{{ checksum "code/package-lock.json" }}
              paths:
                - code/node_modules
      test:
        executor: node
        steps:
          - run:
              name: Running make test
              command: make test
      lint:
        executor: node
        steps:
          - run:
              name: Running make lint
              command: make lint
      build:
        executor: node
        steps:
          - run:
              name: Running make build
              command: make build
      deploy:
        executor: node
        steps:
          - run:
              name: Running make deploy
              command: make deploy

jobs:

workflows:
  main:
    jobs:
      - node/checkout
      - node/install:
          requires:
            - node/checkout
      - node/verify-versions:
          requires:
            - node/install
      # - node/checkout
      # - node/init:
      #     requires:
      #       - node/checkout
      # - node/build:
      #     requires:
      #       - node/init
      # - node/test:
      #     requires:
      #       - node/build
      # - node/deploy:
      #     requires:
      #       - node/test
