version: 2.1
description: # The purpose of this orb

orbs:
  node:
    executors:
      node:
        docker:
          - image: cimg/node:10.20
      aws-cli:
        docker:
          - image: amazon/aws-cli
    # commands:
    #   install:
    #     steps:
    #       - run:
    #           name: Install NVM
    #           command: curl -o- https://raw.githubusercontent.com/creationix/nvm/v${NVM_VERSION}/install.sh | bash \
    #       - run:
    #           name: activate profile
    #           command: |
    #             echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
    #             echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV

    jobs:
      verify-versions:
        executor: node
        steps:
          - run:
              name: npm version
              command: npm --version
          - run:
              name: node version
              command: node --version
      init:
        executor: node
        steps:
          - run:
              name: Running make init
              command: make init
          - persist_to_workspace:
              root: .
              paths:
                - .
      test:
        executor: node
        steps:
          - run:
              name: Running make test
              command: make test
      lint:
        executor: node
        steps:
          - run:
              name: Running make lint
              command: make lint
      build:
        executor: node
        steps:
          - attach_workspace:
              at: .
          - run:
              name: Running make build
              command: make build
      deploy:
        executor: node
        steps:
          - run:
              name: Running make deploy
              command: make deploy

executors:
  python_with_node_image:
    docker:
      - image: circleci/python:3.6.6-stretch-node

jobs:
  development:
    executors: python_with_node_image
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "code/package-lock.json" }}
            - npm-deps-
      - node/init
      - save_cache:
          key: npm-deps-{{ checksum "code/package-lock.json" }}
          paths:
            - code/node_modules
      - node/build
      - node/test
      - node/deploy
  test:
    executors: python_with_node_image
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "code/package-lock.json" }}
            - npm-deps-
      - node/init
      - save_cache:
          key: npm-deps-{{ checksum "code/package-lock.json" }}
          paths:
            - code/node_modules
      - node/build
      - node/test
      - node/deploy
  production:
    executors: python_with_node_image
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "code/package-lock.json" }}
            - npm-deps-
      - node/init
      - save_cache:
          key: npm-deps-{{ checksum "code/package-lock.json" }}
          paths:
            - code/node_modules
      - node/build
      - node/test
      - node/deploy
workflows:
  main:
    jobs:
      - development
      - test:
          requires:
            - developm  ent
      - production:
          requires:
            - production
