version: 2.1
description: # The purpose of this orb

orbs:
  node:
    executors:
      node:
        docker:
          - image: cimg/node:10.20
      aws-cli:
        docker:
          - image: amazon/aws-cli
    jobs:
      verify-versions:
        executor: node
        steps:
          - run:
              name: npm version
              command: npm --version
          - run:
              name: node version
              command: node --version
      init:
        executor: node
        steps:
          - restore_cache:
              keys:
                - npm-deps-{{ checksum "code/package-lock.json" }}
                - npm-deps-
          - run:
              name: Running make init
              command: make init
          - save_cache:
              key: npm-deps-{{ checksum "code/package-lock.json" }}
              paths:
                - code/node_modules
      test:
        executor: node
        steps:
          - run:
              name: Running make test
              command: make test
      lint:
        executor: node
        steps:
          - run:
              name: Running make lint
              command: make lint
      build:
        executor: node
        steps:
          - run:
              name: Running make build
              command: make build
      deploy-development:
        executor: node
        steps:
          - run:
              name: Running make deploy
              command: make deploy
      deploy-test:
        executor: node
        steps:
          - run:
              name: Running make deploy
              command: make deploy
      deploy-production:
        executor: node
        steps:
          - run:
              name: Running make deploy
              command: make deploy
jobs:
  checkout:
    executor: node/aws-cli
    steps:
      - checkout

workflows:
  main:
    jobs:
      - node/verify-versions
      - checkout
      - node/init:
          requires:
            - checkout
      - node/build:
          requires:
            - node/init
      - node/test:
          requires:
            - node/build
      - node/deploy-development:
          requires:
            - node/test
      - node/deploy-test:
          requires:
            - node/deploy-development
      - node/deploy-production:
          requires:
            - node/deploy-test
