version: 2.1
description: # The purpose of this orb

orbs:
  node:
    executors:
      node:
        docker:
          - image: cimg/python:3.7-node
    commands:
      install:
        steps:
          - run: echo "We will now do special things"
    jobs:
      install:
        executor: node
        steps:
          - run:
              name: npm version
              command: npm --version
          - run:
              name: node version
              command: node --version

workflows:
  main:
    jobs:
      - node
