version: 2.1
description: # The purpose of this orb

orbs:
  node:
    executors:
      default:
        docker:
          - image: cimg/node:10.20
      aws-cli:
        docker:
          - image: amazon/aws-cli
    commands:
      init_command:
        description: "make init command"
        parameters:
          init_command:
            type: string
            default: make init
          cache_key:
            type: string
            default: "code/package-lock.json"
          node_modules_path:
            type: string
            default: "code/node_modules"
        steps:
          - checkout
          - restore_cache:
              keys:
                - npm-deps-{{ checksum "<< parameters.cache_key >>" }}
                - npm-deps-
          - run: "<< parameters.init_command >>"
          - save_cache:
              key: npm-deps-{{ checksum "code/applications/preact-app/package-lock.json" }}
              paths:
                - << parameters.node_modules_path >>
      build_command:
        description: "make build command"
        parameters:
          build_command:
            type: string
            default: make build
        steps:
          - run: "<< parameters.build_command >>"
      deploy:
        description: "make deploy command"
        parameters:
          deploy_command:
            type: string
            default: make deploy
        steps:
          - attach_workspace:
              at: .
          - run: "<< parameters.deploy_command >>"
    jobs:
      init:
        executor: default
        steps:
          - init_command
          - persist_to_workspace:
              root: .
              paths:
                - .
      build:
        executor: default
        steps:
          - attach_workspace:
              at: .
          - build_command

jobs:
  deploy-development:
    executor: node/default
    steps:
      - node/deploy
  deploy-test:
    executor: node/default
    steps:
      - node/deploy
  deploy-production:
    executor: node/default
    steps:
      - node/deploy
  # deploy-test:
  #   executor: node/default
  #   steps:
  # deploy-prod:
  #   executor: node/default
  #   steps:

workflows:
  main:
    jobs:
      - node/init
      - node/build:
          requires:
            - node/init
      - deploy-development:
          requires:
            - node/build
      - deploy-test:
          requires:
            - deploy-development
      - deploy-production:
          requires:
            - deploy-test
